On the foucs of labour statistics as of May 2025's release, Canada is seeing unemployment levels as high as what we saw during the Covid-19 layoffs in 2021 again for the first time. Adjusted for seasonality, it hit 6.9% in April 2025 and is at 7% for May.

In [7]:
import pandas as pd
unemp = pd.read_csv('unemployment.csv')
unemp = unemp.filter(items=['REF_DATE', 'Gender', 'Age group', 'VALUE'])
unemp = unemp[unemp['Gender'] == "Total - Gender"]
unemp = unemp[unemp['Age group'] == "15 years and over"]
unemp

   REF_DATE          Gender          Age group  VALUE
0   2024-05  Total - Gender  15 years and over    6.3
1   2024-06  Total - Gender  15 years and over    6.2
2   2024-07  Total - Gender  15 years and over    6.7
3   2024-08  Total - Gender  15 years and over    7.5
4   2024-09  Total - Gender  15 years and over    6.0
5   2024-10  Total - Gender  15 years and over    6.0
6   2024-11  Total - Gender  15 years and over    6.5
7   2024-12  Total - Gender  15 years and over    6.2
8   2025-01  Total - Gender  15 years and over    7.1
9   2025-02  Total - Gender  15 years and over    6.7
10  2025-03  Total - Gender  15 years and over    7.1
11  2025-04  Total - Gender  15 years and over    7.0
12  2025-05  Total - Gender  15 years and over    7.0